Manage pod
jointwt/twtxt pull request #170
Opened 2020-09-06 08:05 UTC by shahxeb

2020-09-06 10:26 UTC, prologic requested changes
Looks mostly okay to me. Basically what we expect! 👍 

Please fix the conflicts so I can test this!

2020-09-06 10:26 UTC, prologic commented on internal/config.go
> +	"github.com/apex/log"
Please use logrus :)

2020-09-10 13:04 UTC, prologic commented
Fixed a few issues in this PR that were the result of bad merge I think.

There is still one outstanding problem; the "configuration" changes don't persist after a restart. I can see they are written to a config file, but we don't seem to load that config file back at all.

2020-09-19 21:08 UTC, aaadonai commented on internal/config.go
> +	Description string `yaml:"pod_descriptio"`
missing the last n on description.

2020-09-19 23:53 UTC, prologic commented on internal/config.go
> +	Description string `yaml:"pod_descriptio"`
Thanks!

2020-09-19 23:54 UTC, prologic commented
I just need to rebase this and resolve the conflicts (_its a bit of a mess unfortunately_) and we can merge this!

2020-09-20 23:54 UTC, prologic approved these changes

2020-09-21 00:03 UTC, merged