[Enhancement] Issue174 - Persist Title and Text of Twts and Twt Blog posts
jointwt/twtxt pull request #193
Opened 2020-09-12 03:38 UTC by gioperazzo

##### Summary

##### Component Name

##### Test Plan

##### Additional Information

2020-09-12 04:05 UTC, dooven commented on internal/static/js/99-twtxt.js
> +  if (title) localStorage.setItem('title', JSON.stringify(title));
Just wondering when this data gets cleared from local storage

2020-09-12 06:38 UTC, prologic commented on internal/static/js/99-twtxt.js
> +  if (title) localStorage.setItem('title', JSON.stringify(title));
Good question! @gioperazzo ?

2020-09-12 11:25 UTC, gioperazzo commented on internal/static/js/99-twtxt.js
> +  if (title) localStorage.setItem('title', JSON.stringify(title));
when clicking the post button, this will be cleared. Please check the code part when clicking the submit button.

2020-09-12 20:58 UTC, prologic requested changes
Looking good. Found a bug however when clicking the "Quill" button to write a Twt Blog:

<img width="1312" alt="Screen Shot 2020-09-13 at 6 57 50 AM" src="https://user-images.githubusercontent.com/1290234/93004865-8b553600-f58e-11ea-8383-6ce938066148.png">

2020-09-12 23:45 UTC, gioperazzo commented
> Looking good. Found a bug however when clicking the "Quill" button to write a Twt Blog:
> 
> <img alt="Screen Shot 2020-09-13 at 6 57 50 AM" width="1312" src="https://user-images.githubusercontent.com/1290234/93004865-8b553600-f58e-11ea-8383-6ce938066148.png">
I think, this bug has happened because the twtxt.min.js has been not updated for some reason. Let me update it.

2020-09-13 00:06 UTC, prologic commented
> I think, this bug has happened because the twtxt.min.js has been not updated for some reason. Let me update it.

The `make build` step is suppose to do this. I use [this tool](https://github.com/tdewolff/minify) to do the job. is this how' you're updating it? Please say yes :) I'll re-test shortly...

2020-09-13 00:08 UTC, prologic commented
> > I think, this bug has happened because the twtxt.min.js has been not updated for some reason. Let me update it.
> 
> The `make build` step is suppose to do this. I use [this tool](https://github.com/tdewolff/minify) to do the job. is this how' you're updating it? Please say yes :) I'll re-test shortly...

The fact that I get differences suggests to me you are missing some tools on your dev machine.

```#!console
prologic@Jamess-iMac
Sun Sep 13 10:07:38
~/Projects/jointwt/twtxt
 (feature174/persist) 0
$ git st
On branch feature174/persist
Your branch is up to date with 'origin/feature174/persist'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   internal/static/js/twtxt.min.js

no changes added to commit (use "git add" and/or "git commit -a")
```

Can you run `make deps` and re-run `make build` and re-test? Thanks ;)

2020-09-13 00:11 UTC, prologic commented
I can still reproduce the bug locally -- even after a `make build` which re-generates the assets.
(_I need to add in a way to do JS/CSS debugging..._)

2020-09-13 00:12 UTC, prologic commented
Also:

<img width="799" alt="Screen Shot 2020-09-13 at 10 11 42" src="https://user-images.githubusercontent.com/1290234/93007212-894ca080-f5a9-11ea-83b2-4b65206ce9a9.png">

Maybe also rebase on top of recent master :)

2020-09-13 00:19 UTC, gioperazzo commented
I am not reproducing the error in my side. I used to remove the cache before retesting because the js code has been cached in browser.

2020-09-13 00:49 UTC, gioperazzo commented
can you please check again? I've rebased and updated. thanks

2020-09-13 01:24 UTC, prologic commented
> I am not reproducing the error in my side. I used to remove the cache before retesting because the js code has been cached in browser.

I used Incognito mode to do dev and test cycles :)

2020-09-13 01:25 UTC, prologic commented
> can you please check again? I've rebased and updated. thanks

Just heading out for a family drive, I'll be able to re-test later. Maybe if @aaadonai or @dooven are able to test, they can approve and merge for you. The pods are all on an automated CD pioeline, so if approved/merged your feature will go in within ~5mins.

2020-09-13 01:32 UTC, aaadonai approved these changes

2020-09-13 05:09 UTC, prologic approved these changes

2020-09-13 05:09 UTC, merged