Add improved async media upload endpoint for the API (backwards compatible)
jointwt/twtxt pull request #274
Opened 2020-11-15 05:33 UTC by prologic

##### Summary

ssia

This _should_ be backwards compatible with older Goryon clients, which
we can easily test since the dev team users both the production version
as well as a internal beta version.

##### Component Name

- area/backend

##### Test Plan

@dooven to test :D

##### Additional Information

Closes #266

2020-11-15 23:27 UTC, aaadonai approved these changes

2020-11-15 23:37 UTC, dooven commented on internal/api.go
> +		if r.UserAgent() == "" {
The old version sends a default user agent that looks like this `Dart/2.11 (dart:io)`. Maybe we can make it so that it'll match if the user agent starts with `Dart`? 

Sorry, i forgot to mention this
![image](https://user-images.githubusercontent.com/15314237/99200136-2625e880-2769-11eb-9869-666cac9ef0d4.png)

2020-11-15 23:37 UTC, dooven approved these changes

2020-11-15 23:38 UTC, dooven requested changes
See comment https://github.com/jointwt/twtxt/pull/274/files/fc0158518e9ac0caf2887b7453e6e7ac27a349c0#r523831739

2020-11-27 11:15 UTC, prologic commented on internal/api.go
> +		if r.UserAgent() == "" {
Fixed

2020-11-27 21:44 UTC, aaadonai approved these changes

2020-12-07 02:36 UTC, dooven approved these changes

2020-12-07 02:49 UTC, merged