i18n: pages and messages
jointwt/twtxt pull request #426
Opened 2021-05-10 16:09 UTC by venjiang

### i18n others

- delete account page 
- external page message
- mentions/feeds/settings page message 
- permalink page message 
- archive feed page message
- user config page message
- post page message

2021-05-13 07:46 UTC, der-lyse requested changes
Apart from the copied typo this looks good to me. Disclaimer: I don't know anything about Chinese.

2021-05-13 07:46 UTC, der-lyse commented on internal/langs/active.en.toml
> +ErrorDeletingAccount = "An error occured whilst deleting your account"
"occurred" is spelt with double "r".

2021-05-13 14:31 UTC, venjiang commented on internal/langs/active.en.toml
> +ErrorDeletingAccount = "An error occured whilst deleting your account"
What happened?

2021-05-14 23:37 UTC, prologic requested changes
Fix the typo or accept my suggested change and we're good to go :)

2021-05-14 23:37 UTC, prologic commented on internal/langs/active.en.toml
> +ErrorDeletingAccount = "An error occured whilst deleting your account"
```suggestion
ErrorDeletingAccount = "An error occurred whilst deleting your account"
```

2021-05-15 13:04 UTC, venjiang commented on internal/langs/active.en.toml
> +ErrorDeletingAccount = "An error occured whilst deleting your account"
🤝

2021-05-15 13:10 UTC, venjiang commented on internal/langs/active.en.toml
> +ErrorDeletingAccount = "An error occured whilst deleting your account"
The en message change causes the hash value of the message key in other languages to change. I will submit it again

2021-05-15 20:47 UTC, prologic approved these changes

2021-05-15 20:48 UTC, prologic commented
cc @der-lyse

2021-05-15 22:19 UTC, der-lyse approved these changes
Commits look a bit messed up, but this doesn't matter, since it's all rebased and squashed anyways. Great work!

2021-05-15 22:20 UTC, merged